# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

[
  "Jeremie Cronin",
  "Ms. Athena Veum",
  "Flavio Murazik",
  "Mr. Jorge Batz",
  "Arianna West",
  "Claudia Kautzer",
  "Logan Tillman",
  "Moriah Will",
  "Marlon Littel",
  "Wiley Hoeger",
  "Ivory Monahan",
  "Jimmy Connelly IV",
  "Dejah Auer",
  "Max Thiel",
  "Dario Ernser",
  "Henri Kuhlman",
  "Torrance Nitzsche",
  "Keyshawn Lakin",
  "Marcelina Veum",
  "Emory Yundt PhD",
  "Sarai Hodkiewicz",
  "Luis Bergnaum Jr.",
  "Ms. Kenya Kuhlman",
  "Montana Champlin",
  "Elias Rutherford",
  "Mrs. Alessandro Gleason",
  "Doyle Nader",
  "Shanon Pagac",
  "Micheal DuBuque III",
  "Velva Buckridge",
  "Cheyenne Langworth",
  "Violette Heaney",
  "Mr. Granville Brown",
  "Clotilde Wyman Jr.",
  "Linnea Nicolas III",
  "Griffin Bins",
  "Henry Gutkowski",
  "Melyssa Veum",
  "Lou Kirlin",
  "Jarvis Schinner",
  "Michel Schamberger",
  "Vincenzo Farrell",
  "Dayton Streich",
  "Federico Lebsack IV",
  "Jillian Gottlieb",
  "Miss Filomena Muller",
  "Samson Lind Jr.",
  "Mr. Chandler Thompson",
  "Miss Marie Nolan",
  "Breana Johnston",
  "Carmen McLaughlin",
  "Chesley Turner",
  "Loma Brekke",
  "Enid Labadie DVM",
  "Orion Schmeler",
  "Thurman Schaden",
  "Genesis Schmitt",
  "Lavinia Bogisich",
  "Savanna Kautzer",
  "Mariah Runolfsson",
  "Russ Quigley",
  "Mr. Noble Rice",
  "Cletus Effertz",
  "Yoshiko Rodriguez",
  "Gerhard Kuphal",
  "Morgan Mertz",
  "Conor Dietrich",
  "Maryjane Bosco",
  "Stephanie McCullough",
  "Dr. Ramiro Kutch",
  "Casper Powlowski",
  "Miss Alexanne Stiedemann",
  "Larue Metz",
  "Adela Smith",
  "Rebecca Franecki",
].each_with_index do |name, i|
  User.create name: name, email: "user#{i}@example.com"
end
